[package]

name = "bulkhead"
version = "0.0.1"
authors = ["John Barker <jebarker@gmail.com>"]

[dependencies]

bodyparser = "*"
hyper = "*"
iron = "*"
postgres = "*"
router = "*"
rustc-serialize = "*"
time = "*"
